# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += core gui multimedia multimediawidgets
TEMPLATE = app
TARGET = SomLauncherCpp
DESTDIR = ../x64/Debug
CONFIG += debug console
CONFIG += x86_64
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
SOURCES += main.cpp
include(SomLauncherCpp.pri)
